services:
  - type: web
    name: weekend-weather-planner
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
  - type: web
    name: gstrdnmc-bot
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
