interface TransportConfig {
    apiName: string;
    displayName: string;
    provider: "yandex" | "aeroflot";
    yandexId?: string;
    stationTo: string;
    stationFrom: string;
    moscowStation: string;
}

export const CITY_TRANSPORT_CONFIG: Record<string, TransportConfig> = {
    "Александров": {
        apiName: "Александров-1",
        displayName: "Александров-1",
        provider: "yandex",
        yandexId: "s9601628",
        stationTo: "Александров-1",
        stationFrom: "Александров-1",
        moscowStation: "Ярославский вокзал",
    },
    "Воскресенск": {
        apiName: "88 км",
        displayName: "88 км",
        provider: "yandex",
        yandexId: "s9601903",
        stationTo: "88 км",
        stationFrom: "88 км",
        moscowStation: "Казанский вокзал",
    },
    "Волоколамск": {
        apiName: "Волоколамск",
        displayName: "Волоколамск",
        provider: "yandex",
        yandexId: "s9600995",
        stationTo: "Волоколамск",
        stationFrom: "Волоколамск",
        moscowStation: "Рижский вокзал",
    },
    "Дубна": {
        apiName: "Большая Волга",
        displayName: "Большая Волга",
        provider: "yandex",
        yandexId: "s9601720",
        stationTo: "Большая Волга",
        stationFrom: "Большая Волга",
        moscowStation: "Савёловский вокзал",
    },
    "Завидово": {
        apiName: "Новозавидовский",
        displayName: "Новозавидовский",
        provider: "yandex",
        yandexId: "c22478",
        stationTo: "Новозавидовский",
        stationFrom: "Новозавидовский",
        moscowStation: "Ленинградский вокзал",
    },
    "Звенигород": {
        apiName: "Звенигород",
        displayName: "Звенигород",
        provider: "yandex",
        yandexId: "s9601017",
        stationTo: "Звенигород",
        stationFrom: "Звенигород",
        moscowStation: "Белорусский вокзал",
    },
    "Зеленоград": {
        apiName: "Крюково",
        displayName: "Крюково",
        provider: "yandex",
        yandexId: "s9602403",
        stationTo: "Крюково",
        stationFrom: "Крюково",
        moscowStation: "Ленинградский вокзал",
    },
    "Истра": {
        apiName: "Истра",
        displayName: "Истра",
        provider: "yandex",
        yandexId: "s9600984",
        stationTo: "Истра",
        stationFrom: "Истра",
        moscowStation: "Рижский вокзал",
    },
    "Коломна": {
        apiName: "Голутвин",
        displayName: "Голутвин",
        provider: "yandex",
        yandexId: "s9600716",
        stationTo: "Голутвин",
        stationFrom: "Голутвин",
        moscowStation: "Казанский вокзал",
    },
    "Кубинка": {
        apiName: "Кубинка-1",
        displayName: "Кубинка-1",
        provider: "yandex",
        yandexId: "s9601004",
        stationTo: "Кубинка-1",
        stationFrom: "Кубинка-1",
        moscowStation: "Белорусский вокзал",
    },
    "Калуга": {
        apiName: "Калуга-1",
        displayName: "Калуга-1",
        provider: "yandex",
        yandexId: "s9600866",
        stationTo: "Калуга-1",
        stationFrom: "Калуга-1",
        moscowStation: "Киевский вокзал",
    },
    "Кемер": {
        apiName: "AYT",
        displayName: "Анталья",
        provider: "aeroflot",
        stationTo: "AYT",
        stationFrom: "AYT",
        moscowStation: "Москва",
    },
    "Можайск": {
        apiName: "Можайск",
        displayName: "Можайск",
        provider: "yandex",
        yandexId: "s9600943",
        stationTo: "Можайск",
        stationFrom: "Можайск",
        moscowStation: "Белорусский вокзал",
    },
    "Наро-Фоминск": {
        apiName: "Нара",
        displayName: "Нара",
        provider: "yandex",
        yandexId: "s9600823",
        stationTo: "Нара",
        stationFrom: "Нара",
        moscowStation: "Киевский вокзал",
    },
    "Обнинск": {
        apiName: "Обнинское",
        displayName: "Обнинское",
        provider: "yandex",
        yandexId: "s9600844",
        stationTo: "Обнинское",
        stationFrom: "Обнинское",
        moscowStation: "Киевский вокзал",
    },
    "Подольск": {
        apiName: "Подольск",
        displayName: "Подольск",
        provider: "yandex",
        yandexId: "s9600781",
        stationTo: "Подольск",
        stationFrom: "Подольск",
        moscowStation: "Курский вокзал",
    },
    "Павловский Посад": {
        apiName: "Павловский Посад",
        displayName: "Павловский Посад",
        provider: "yandex",
        yandexId: "s9601872",
        stationTo: "Павловский Посад",
        stationFrom: "Павловский Посад",
        moscowStation: "Курский вокзал",
    },
    "Пушкино": {
        apiName: "Пушкино",
        displayName: "Пушкино",
        provider: "yandex",
        yandexId: "s9601588",
        stationTo: "Пушкино",
        stationFrom: "Пушкино",
        moscowStation: "Ярославский вокзал",
    },
    "Рязань": {
        apiName: "Рязань-1",
        displayName: "Рязань-1",
        provider: "yandex",
        yandexId: "s9600624",
        stationTo: "Рязань-1",
        stationFrom: "Рязань-1",
        moscowStation: "Казанский вокзал",
    },
    "Сергиев Посад": {
        apiName: "Сергиев Посад",
        displayName: "Сергиев Посад",
        provider: "yandex",
        yandexId: "s9601614",
        stationTo: "Сергиев Посад",
        stationFrom: "Сергиев Посад",
        moscowStation: "Ярославский вокзал",
    },
    "Солнечногорск": {
        apiName: "Подсолнечная",
        displayName: "Подсолнечная",
        provider: "yandex",
        stationTo: "Подсолнечная",
        stationFrom: "Подсолнечная",
        moscowStation: "Ленинградский вокзал",
    },
    "Серпухов": {
        apiName: "Серпухов",
        displayName: "Серпухов",
        provider: "yandex",
        yandexId: "s9600758",
        stationTo: "Серпухов",
        stationFrom: "Серпухов",
        moscowStation: "Курский вокзал",
    },
    "Ступино": {
        apiName: "Ступино",
        displayName: "Ступино",
        provider: "yandex",
        yandexId: "s9600732",
        stationTo: "Ступино",
        stationFrom: "Ступино",
        moscowStation: "Павелецкий вокзал",
    },
    "Тула": {
        apiName: "Тула-1-Курская",
        displayName: "Тула",
        provider: "yandex",
        yandexId: "s9600742",
        stationTo: "Тула-1-Курская",
        stationFrom: "Тула-1-Курская",
        moscowStation: "Курский вокзал",
    },
    "Фетхие": {
        apiName: "DLM",
        displayName: "Даламан",
        provider: "aeroflot",
        stationTo: "DLM",
        stationFrom: "DLM",
        moscowStation: "Москва",
    },
    "Яхрома": {
        apiName: "Яхрома",
        displayName: "Яхрома",
        provider: "yandex",
        yandexId: "s9601675",
        stationTo: "Яхрома",
        stationFrom: "Яхрома",
        moscowStation: "Савёловский вокзал",
    },
};
