interface TransportConfig {
    apiName: string;
    displayName: string;
    provider: "yandex" | "aeroflot";
    yandexId?: string;
    stationTo: string;
    stationFrom: string;
    moscowStation: string;
}

export const MOSCOW_STATION_YANDEX_IDS: Record<string, string> = {
    "Ярославский вокзал": "s9600234",
    "Казанский вокзал": "s9600213",
    "Курский вокзал": "s9600216",
    "Савёловский вокзал": "s9600235",
    "Ленинградский вокзал": "s9600224",
    "Белорусский вокзал": "s9600215",
    "Киевский вокзал": "s9600217",
    "Павелецкий вокзал": "s9600238",
    "Рижский вокзал": "s9600225",
    // Add more if needed
};

export const CITY_TRANSPORT_CONFIG: Record<string, TransportConfig> = {
    "Александров": {
        apiName: "Александров-1",
        displayName: "Александров-1",
        provider: "yandex",
        yandexId: "s9601547",
        stationTo: "Александров-1",
        stationFrom: "Александров-1",
        moscowStation: "Ярославский вокзал",
    },
    "Воскресенск": {
        apiName: "88 км",
        displayName: "88 км",
        provider: "yandex",
        yandexId: "s9601903",
        stationTo: "88 км",
        stationFrom: "88 км",
        moscowStation: "Казанский вокзал",
    },
    "Волоколамск": {
        apiName: "Волоколамск",
        displayName: "Волоколамск",
        provider: "yandex",
        yandexId: "s9600696",
        stationTo: "Волоколамск",
        stationFrom: "Волоколамск",
        moscowStation: "Рижский вокзал",
    },
    "Дубна": {
        apiName: "Большая Волга",
        displayName: "Большая Волга",
        provider: "yandex",
        yandexId: "s9601720",
        stationTo: "Большая Волга",
        stationFrom: "Большая Волга",
        moscowStation: "Савёловский вокзал",
    },
    "Жуковский": {
        apiName: "Отдых",
        displayName: "Отдых",
        provider: "yandex",
        yandexId: "s9602223",
        stationTo: "Отдых",
        stationFrom: "Отдых",
        moscowStation: "Казанский вокзал",
    },
    "Завидово": {
        apiName: "Новозавидовский",
        displayName: "Новозавидовский",
        provider: "yandex",
        yandexId: "c22478",
        stationTo: "Новозавидовский",
        stationFrom: "Новозавидовский",
        moscowStation: "Ленинградский вокзал",
    },
    "Звенигород": {
        apiName: "Звенигород",
        displayName: "Звенигород",
        provider: "yandex",
        yandexId: "s9601368",
        stationTo: "Звенигород",
        stationFrom: "Звенигород",
        moscowStation: "Белорусский вокзал",
    },
    "Зеленоград": {
        apiName: "Крюково",
        displayName: "Крюково",
        provider: "yandex",
        yandexId: "s9600212",
        stationTo: "Крюково",
        stationFrom: "Крюково",
        moscowStation: "Ленинградский вокзал",
    },
    "Истра": {
        apiName: "Истра",
        displayName: "Истра",
        provider: "yandex",
        yandexId: "s9601923",
        stationTo: "Истра",
        stationFrom: "Истра",
        moscowStation: "Курский вокзал",
    },
    "Коломна": {
        apiName: "Голутвин",
        displayName: "Голутвин",
        provider: "yandex",
        yandexId: "s9600716",
        stationTo: "Голутвин",
        stationFrom: "Голутвин",
        moscowStation: "Казанский вокзал",
    },
    "Кубинка": {
        apiName: "Кубинка 1",
        displayName: "Кубинка 1",
        provider: "yandex",
        yandexId: "s9600748",
        stationTo: "Кубинка 1",
        stationFrom: "Кубинка 1",
        moscowStation: "Белорусский вокзал",
    },
    "Калуга": {
        apiName: "Калуга-1",
        displayName: "Калуга-1",
        provider: "yandex",
        yandexId: "s2000345",
        stationTo: "Калуга-1",
        stationFrom: "Калуга-1",
        moscowStation: "Киевский вокзал",
    },
    "Кемер": {
        apiName: "AYT",
        displayName: "Анталья",
        provider: "aeroflot",
        stationTo: "AYT",
        stationFrom: "AYT",
        moscowStation: "Москва",
    },
    "Можайск": {
        apiName: "Можайск",
        displayName: "Можайск",
        provider: "yandex",
        yandexId: "s9601006",
        stationTo: "Можайск",
        stationFrom: "Можайск",
        moscowStation: "Белорусский вокзал",
    },
    "Наро-Фоминск": {
        apiName: "Нара",
        displayName: "Нара",
        provider: "yandex",
        yandexId: "s9601137",
        stationTo: "Нара",
        stationFrom: "Нара",
        moscowStation: "Киевский вокзал",
    },
    "Обнинск": {
        apiName: "Обнинское",
        displayName: "Обнинское",
        provider: "yandex",
        yandexId: "s9601907",
        stationTo: "Обнинское",
        stationFrom: "Обнинское",
        moscowStation: "Киевский вокзал",
    },
    "Одинцово": {
        apiName: "Одинцово",
        displayName: "Одинцово",
        provider: "yandex",
        yandexId: "s9600721",
        stationTo: "Одинцово",
        stationFrom: "Одинцово",
        moscowStation: "Белорусский вокзал",
    },
    "Подольск": {
        apiName: "Подольск",
        displayName: "Подольск",
        provider: "yandex",
        yandexId: "s9600731",
        stationTo: "Подольск",
        stationFrom: "Подольск",
        moscowStation: "Курский вокзал",
    },
    "Павловский Посад": {
        apiName: "Павловский Посад",
        displayName: "Павловский Посад",
        provider: "yandex",
        yandexId: "s9601872",
        stationTo: "Павловский Посад",
        stationFrom: "Павловский Посад",
        moscowStation: "Курский вокзал",
    },
    "Пушкино": {
        apiName: "Пушкино",
        displayName: "Пушкино",
        provider: "yandex",
        yandexId: "s9600701",
        stationTo: "Пушкино",
        stationFrom: "Пушкино",
        moscowStation: "Ярославский вокзал",
    },
    "Рязань": {
        apiName: "Рязань-1",
        displayName: "Рязань-1",
        provider: "yandex",
        yandexId: "s9600786",
        stationTo: "Рязань-1",
        stationFrom: "Рязань-1",
        moscowStation: "Казанский вокзал",
    },
    "Сергиев Посад": {
        apiName: "Сергиев Посад",
        displayName: "Сергиев Посад",
        provider: "yandex",
        yandexId: "s9601389",
        stationTo: "Сергиев Посад",
        stationFrom: "Сергиев Посад",
        moscowStation: "Ярославский вокзал",
    },
    "Солнечногорск": {
        apiName: "Подсолнечная",
        displayName: "Подсолнечная",
        provider: "yandex",
        yandexId: "s9603468",
        stationTo: "Подсолнечная",
        stationFrom: "Подсолнечная",
        moscowStation: "Ленинградский вокзал",
    },
    "Серпухов": {
        apiName: "Серпухов",
        displayName: "Серпухов",
        provider: "yandex",
        yandexId: "s9600830",
        stationTo: "Серпухов",
        stationFrom: "Серпухов",
        moscowStation: "Курский вокзал",
    },
    "Ступино": {
        apiName: "Ступино",
        displayName: "Ступино",
        provider: "yandex",
        yandexId: "s9601202",
        stationTo: "Ступино",
        stationFrom: "Ступино",
        moscowStation: "Павелецкий вокзал",
    },
    "Тула": {
        apiName: "Тула Московский вокзал",
        displayName: "Тула",
        provider: "yandex",
        yandexId: "s9623131",
        stationTo: "Тула Московский вокзал",
        stationFrom: "Тула Московский вокзал",
        moscowStation: "Курский вокзал",
    },
    "Фетхие": {
        apiName: "DLM",
        displayName: "Даламан",
        provider: "aeroflot",
        stationTo: "DLM",
        stationFrom: "DLM",
        moscowStation: "Москва",
    },
    "Яхрома": {
        apiName: "Яхрома",
        displayName: "Яхрома",
        provider: "yandex",
        yandexId: "s9737523",
        stationTo: "Яхрома",
        stationFrom: "Яхрома",
        moscowStation: "Савёловский вокзал",
    },
    "Москва": {
        apiName: "Москва",
        displayName: "Москва",
        provider: "yandex",
        yandexId: "c213",
        stationTo: "Москва",
        stationFrom: "Москва",
        moscowStation: "Москва",
    },
};
