import { CityMap, Place, FlightCities } from "../types";

export const CITIES: CityMap = {
    "Москва": { lat: 55.75, lon: 37.61 },
    "Истра": { lat: 55.91, lon: 36.85 },
    "Кубинка": { lat: 55.59, lon: 36.72 },
    "Можайск": { lat: 55.50, lon: 36.03 },
    "Волоколамск": { lat: 56.04, lon: 35.96 },
    "Солнечногорск": { lat: 56.18, lon: 36.98 },
    "Завидово": { lat: 56.52, lon: 36.52 },
    "Дубна": { lat: 56.73, lon: 37.16 },
    "Яхрома": { lat: 56.29, lon: 37.48 },
    "Сергиев Посад": { lat: 56.30, lon: 38.13 },
    "Александров": { lat: 56.39, lon: 38.71 },
    "Павловский Посад": { lat: 55.78, lon: 38.65 },
    "Воскресенск": { lat: 55.32, lon: 38.68 },
    "Коломна": { lat: 55.08, lon: 38.78 },
    "Ступино": { lat: 54.89, lon: 38.08 },
    "Серпухов": { lat: 54.91, lon: 37.41 },
    "Калуга": { lat: 54.51, lon: 36.26 },
    "Обнинск": { lat: 55.11, lon: 36.61 },
    "Наро-Фоминск": { lat: 55.39, lon: 36.73 },
    "Жуковский": { lat: 55.60, lon: 38.12 },
    "Рязань": { lat: 54.62, lon: 39.73 },
    "Одинцово": { lat: 55.67, lon: 37.28 },
    "Зеленоград": { lat: 55.99, lon: 37.21 },
    "Подольск": { lat: 55.43, lon: 37.55 },
    "Тула": { lat: 54.19, lon: 37.61 },
    "Пушкино": { lat: 56.01, lon: 37.85 },
    // "Кемер": { lat: 36.60, lon: 30.56 },
    "Звенигород": { lat: 55.73, lon: 36.86 },
    "Минск": { lat: 53.90, lon: 27.55 },
    "Нижний Новгород": { lat: 56.32, lon: 44.00 },
    "Псков": { lat: 57.81, lon: 28.34 }
};

export const MIN_SUN_HOURS = 6;

// Map Cyrillic City Name -> Latin Filename prefix
export const CITY_FILENAMES: Record<string, string> = {
    "Можайск": "Mozhaysk",
    "Жуковский": "Zhukovskyi",
    "Москва": "Moscow",
    "Истра": "Istra",
    "Кубинка": "Kubinka",
    "Волоколамск": "Volokolamsk",
    "Солнечногорск": "Solnechnogorsk",
    "Завидово": "Zavidovo",
    "Дубна": "Dubna",
    "Яхрома": "Yakhroma",
    "Сергиев Посад": "SergievPosad",
    "Александров": "Alexandrov",
    "Павловский Посад": "PavlovskyPosad",
    "Воскресенск": "Voskresensk",
    "Коломна": "Kolomna",
    "Ступино": "Stupino",
    "Серпухов": "Serpukhov",
    "Калуга": "Kaluga",
    "Обнинск": "Obninsk",
    "Наро-Фоминск": "NaroFominsk",
    "Рязань": "Ryazan",
    "Одинцово": "Odintsovo",
    "Зеленоград": "Zelenograd",
    "Подольск": "Podolsk",
    "Тула": "Tula",
    "Пушкино": "Pushkino",
    "Звенигород": "Zvenigorod",
    // "Кемер": "Kemer",
    "Минск": "Minsk",
    "Нижний Новгород": "NNovgorod",
    "Псков": "Pskov"
};

export const FLIGHT_CITIES: FlightCities = [/*"Кемер"*/];

export const MOUNTAIN_CITIES: string[] = [/*"Кемер",*/ "Фетхие"];

export const HOLIDAYS = [
  "2026-05-01", "2026-05-11", "2026-06-12", "2026-11-04"
];

export const API_URL = "https://api.open-meteo.com/v1/forecast";

// Recommended Places (Gastronomy)
export const CITY_PLACES: Record<string, Place[]> = {
    "Дубна": [
        { name: "Пиццерони", type: "Пиццерия", address: "пр. Боголюбова, 16А", rating: "4.8", url: "https://yandex.ru/maps/-/CDu~mK3j" },
        { name: "Ибару", type: "Кафе", address: "ул. Вернова, 5", rating: "4.7" },
        { name: "Почемучка", type: "Кофейня", address: "ул. Сахарова, 10", rating: "5.0" },
        { name: "Волга-Волга", type: "Ресторан", address: "наб. Менделеева", rating: "4.9" }
    ],
    "Звенигород": [
         { name: "Здесь был Чехов", type: "Кафе", rating: "4.8" },
         { name: "Луковка", type: "Музей-кафе", rating: "4.9" }
    ],
    "Коломна": [
         { name: "Калачная", type: "Музей", rating: "5.0" },
         { name: "Рульки Вверх", type: "Ресторан", rating: "4.7" }
    ]
};

interface TransportConfig {
    apiName: string;
    displayName: string;
    provider: "yandex" | "aeroflot";
    yandexId?: string;
    stationTo: string;
    stationFrom: string;
    moscowStation: string;
    lat?: number;
    lon?: number;
}

export const CITY_TRANSPORT_CONFIG: Record<string, TransportConfig> = {
    "Александров": {
        apiName: "Александров-1",
        displayName: "Александров-1",
        provider: "yandex",
        yandexId: "s9601547",
        stationTo: "Александров-1",
        stationFrom: "Александров-1",
        moscowStation: "Ярославский вокзал",
        lat: 56.394,
        lon: 38.729,
    },
    "Воскресенск": {
        apiName: "88 км",
        displayName: "88 км",
        provider: "yandex",
        yandexId: "s9601903",
        stationTo: "88 км",
        stationFrom: "88 км",
        moscowStation: "Казанский вокзал",
        lat: 55.316,
        lon: 38.681,
    },
    "Волоколамск": {
        apiName: "Волоколамск",
        displayName: "Волоколамск",
        provider: "yandex",
        yandexId: "s9600696",
        stationTo: "Волоколамск",
        stationFrom: "Волоколамск",
        moscowStation: "Курский вокзал",
    },
    "Дубна": {
        apiName: "Большая Волга",
        displayName: "Большая Волга",
        provider: "yandex",
        yandexId: "s9601720",
        stationTo: "Большая Волга",
        stationFrom: "Большая Волга",
        moscowStation: "Савёловский вокзал",
        lat: 56.723,
        lon: 37.143,
    },
    "Жуковский": {
        apiName: "Отдых",
        displayName: "Отдых",
        provider: "yandex",
        yandexId: "s9602223",
        stationTo: "Отдых",
        stationFrom: "Отдых",
        moscowStation: "Казанский вокзал",
    },
    "Завидово": {
        apiName: "Новозавидовский",
        displayName: "Новозавидовский",
        provider: "yandex",
        yandexId: "c22478",
        stationTo: "Новозавидовский",
        stationFrom: "Новозавидовский",
        moscowStation: "Ленинградский вокзал",
        lat: 56.525,
        lon: 36.527,
    },
    "Звенигород": {
        apiName: "Звенигород",
        displayName: "Звенигород",
        provider: "yandex",
        yandexId: "s9601368",
        stationTo: "Звенигород",
        stationFrom: "Звенигород",
        moscowStation: "Белорусский вокзал",
        lat: 55.719,
        lon: 36.883,
    },
    "Зеленоград": {
        apiName: "Крюково",
        displayName: "Крюково",
        provider: "yandex",
        yandexId: "s9600212",
        stationTo: "Крюково",
        stationFrom: "Крюково",
        moscowStation: "Ленинградский вокзал",
        lat: 55.98,
        lon: 37.172,
    },
    "Истра": {
        apiName: "Истра",
        displayName: "Истра",
        provider: "yandex",
        yandexId: "s9601923",
        stationTo: "Истра",
        stationFrom: "Истра",
        moscowStation: "Курский вокзал",
        lat: 55.914,
        lon: 36.857,
    },
    "Коломна": {
        apiName: "Голутвин",
        displayName: "Голутвин",
        provider: "yandex",
        yandexId: "s9600716",
        stationTo: "Голутвин",
        stationFrom: "Голутвин",
        moscowStation: "Казанский вокзал",
        lat: 55.08,
        lon: 38.792,
    },
    "Кубинка": {
        apiName: "Кубинка 1",
        displayName: "Кубинка 1",
        provider: "yandex",
        yandexId: "s9600748",
        stationTo: "Кубинка 1",
        stationFrom: "Кубинка 1",
        moscowStation: "Белорусский вокзал",
    },
    "Калуга": {
        apiName: "Калуга-1",
        displayName: "Калуга-1",
        provider: "yandex",
        yandexId: "s2000345",
        stationTo: "Калуга-1",
        stationFrom: "Калуга-1",
        moscowStation: "Киевский вокзал",
    },
    "Кемер": {
        apiName: "AYT",
        displayName: "Анталья",
        provider: "aeroflot",
        stationTo: "AYT",
        stationFrom: "AYT",
        moscowStation: "Москва",
    },
    "Можайск": {
        apiName: "Можайск",
        displayName: "Можайск",
        provider: "yandex",
        yandexId: "s9601006",
        stationTo: "Можайск",
        stationFrom: "Можайск",
        moscowStation: "Белорусский вокзал",
        lat: 55.495,
        lon: 36.035,
    },
    "Наро-Фоминск": {
        apiName: "Нара",
        displayName: "Нара",
        provider: "yandex",
        yandexId: "s9601137",
        stationTo: "Нара",
        stationFrom: "Нара",
        moscowStation: "Киевский вокзал",
    },
    "Обнинск": {
        apiName: "Обнинское",
        displayName: "Обнинское",
        provider: "yandex",
        yandexId: "s9601907",
        stationTo: "Обнинское",
        stationFrom: "Обнинское",
        moscowStation: "Киевский вокзал",
    },
    "Одинцово": {
        apiName: "Одинцово",
        displayName: "Одинцово",
        provider: "yandex",
        yandexId: "s9600721",
        stationTo: "Одинцово",
        stationFrom: "Одинцово",
        moscowStation: "Белорусский вокзал",
    },
    "Подольск": {
        apiName: "Подольск",
        displayName: "Подольск",
        provider: "yandex",
        yandexId: "s9600731",
        stationTo: "Подольск",
        stationFrom: "Подольск",
        moscowStation: "Курский вокзал",
    },
    "Павловский Посад": {
        apiName: "Павловский Посад",
        displayName: "Павловский Посад",
        provider: "yandex",
        yandexId: "s9601872",
        stationTo: "Павловский Посад",
        stationFrom: "Павловский Посад",
        moscowStation: "Курский вокзал",
        lat: 55.776,
        lon: 38.675,
    },
    "Пушкино": {
        apiName: "Пушкино",
        displayName: "Пушкино",
        provider: "yandex",
        yandexId: "s9600701",
        stationTo: "Пушкино",
        stationFrom: "Пушкино",
        moscowStation: "Ярославский вокзал",
    },
    "Рязань": {
        apiName: "Рязань-1",
        displayName: "Рязань-1",
        provider: "yandex",
        yandexId: "s9600786",
        stationTo: "Рязань-1",
        stationFrom: "Рязань-1",
        moscowStation: "Казанский вокзал",
        lat: 54.9669,
        lon: 39.7356,
    },
    "Сергиев Посад": {
        apiName: "Сергиев Посад",
        displayName: "Сергиев Посад",
        provider: "yandex",
        yandexId: "s9601389",
        stationTo: "Сергиев Посад",
        stationFrom: "Сергиев Посад",
        moscowStation: "Ярославский вокзал",
        lat: 56.302,
        lon: 38.134,
    },
    "Солнечногорск": {
        apiName: "Подсолнечная",
        displayName: "Подсолнечная",
        provider: "yandex",
        yandexId: "s9603468",
        stationTo: "Подсолнечная",
        stationFrom: "Подсолнечная",
        moscowStation: "Ленинградский вокзал",
        lat: 56.182,
        lon: 36.974,
    },
    "Серпухов": {
        apiName: "Серпухов",
        displayName: "Серпухов",
        provider: "yandex",
        yandexId: "s9600830",
        stationTo: "Серпухов",
        stationFrom: "Серпухов",
        moscowStation: "Курский вокзал",
        lat: 54.931,
        lon: 37.452,
    },
    "Ступино": {
        apiName: "Ступино",
        displayName: "Ступино",
        provider: "yandex",
        yandexId: "s9601202",
        stationTo: "Ступино",
        stationFrom: "Ступино",
        moscowStation: "Павелецкий вокзал",
    },
    "Тула": {
        apiName: "Тула Московский вокзал",
        displayName: "Тула",
        provider: "yandex",
        yandexId: "s9623131",
        stationTo: "Тула Московский вокзал",
        stationFrom: "Тула Московский вокзал",
        moscowStation: "Курский вокзал",
    },
    "Фетхие": {
        apiName: "DLM",
        displayName: "Даламан",
        provider: "aeroflot",
        stationTo: "DLM",
        stationFrom: "DLM",
        moscowStation: "Москва",
    },
    "Яхрома": {
        apiName: "Яхрома",
        displayName: "Яхрома",
        provider: "yandex",
        yandexId: "s9737523",
        stationTo: "Яхрома",
        stationFrom: "Яхрома",
        moscowStation: "Савёловский вокзал",
        lat: 56.287,
        lon: 37.489,
    },
    "Москва": {
        apiName: "Москва",
        displayName: "Москва",
        provider: "yandex",
        yandexId: "c213",
        stationTo: "Москва",
        stationFrom: "Москва",
        moscowStation: "Москва",
    },
    "Минск": {
        apiName: "Минск-Пассажирский",
        displayName: "Минск",
        provider: "yandex",
        yandexId: "c157",
        stationTo: "Минск-Пассажирский",
        stationFrom: "Минск-Пассажирский",
        moscowStation: "Белорусский вокзал",
    },
    "Нижний Новгород": {
        apiName: "Нижний Новгород",
        displayName: "Нижний Новгород",
        provider: "yandex",
        yandexId: "c47",
        stationTo: "Нижний Новгород",
        stationFrom: "Нижний Новгород",
        moscowStation: "Восточный вокзал",
    },
    "Псков": {
        apiName: "Псков-Пассажирский",
        displayName: "Псков",
        provider: "yandex",
        yandexId: "c24",
        stationTo: "Псков-Пассажирский",
        stationFrom: "Псков-Пассажирский",
        moscowStation: "Ленинградский вокзал",
    },
};
